# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('BU', 'Business'), ('PE', 'Personal')], max_length=2)),
                ('city', models.CharField(max_length=32, null=True)),
                ('country_code', models.CharField(max_length=2, null=True)),
                ('cc_id', models.CharField(max_length=36)),
                ('line1', models.CharField(max_length=100, null=True)),
                ('line2', models.CharField(max_length=100, null=True)),
                ('line3', models.CharField(max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('state_code', models.CharField(max_length=2, null=True)),
                ('sub_postal_code', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConstantContactList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_id', models.IntegerField()),
                ('status', models.CharField(choices=[('AC', 'Active'), ('HI', 'Hidden')], max_length=2)),
                ('name', models.CharField(max_length=48)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.NullBooleanField()),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField()),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('cc_id', models.IntegerField()),
                ('cc_modified_date', models.DateTimeField()),
                ('prefix_name', models.CharField(max_length=10, null=True)),
                ('job_title', models.CharField(max_length=50, null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('UN', 'Unconfirmed'), ('AC', 'Active'), ('OP', 'Optout'), ('RE', 'Removed'), ('NO', 'Non Subscriber')], max_length=2)),
                ('addresses', models.ManyToManyField(to='datacombine.Address')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_status', models.CharField(choices=[('CO', 'Confirmed'), ('NC', 'No Confirmation Required')], max_length=3)),
                ('cc_id', models.CharField(max_length=36)),
                ('status', models.CharField(choices=[('UN', 'Unconfirmed'), ('AC', 'Active'), ('OP', 'Optout'), ('RE', 'Removed'), ('NO', 'Non Subscriber')], max_length=2)),
                ('opt_in_date', models.DateTimeField(null=True)),
                ('opt_out_date', models.DateTimeField(null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('opt_in_source', models.CharField(choices=[('AO', 'Action by Owner'), ('AV', 'Action by Visitor')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('cc_id', models.CharField(max_length=36)),
                ('modified_date', models.DateTimeField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=3, null=True)),
                ('number', models.CharField(max_length=7)),
                ('extension', models.CharField(max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatusOnCCList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'Active'), ('HI', 'Hidden')], max_length=2)),
                ('cclist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacombine.ConstantContactList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacombine.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='cc_lists',
            field=models.ManyToManyField(through='datacombine.UserStatusOnCCList', to='datacombine.ConstantContactList'),
        ),
        migrations.AddField(
            model_name='contact',
            name='cell_phone',
            field=models.ManyToManyField(related_name='_contact_cell_phone_+', to='datacombine.Phone'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_addresses',
            field=models.ManyToManyField(to='datacombine.EmailAddress'),
        ),
        migrations.AddField(
            model_name='contact',
            name='fax',
            field=models.ManyToManyField(related_name='_contact_fax_+', to='datacombine.Phone'),
        ),
        migrations.AddField(
            model_name='contact',
            name='home_phone',
            field=models.ManyToManyField(related_name='_contact_home_phone_+', to='datacombine.Phone'),
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datacombine.Note'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_phone',
            field=models.ManyToManyField(related_name='_contact_work_phone_+', to='datacombine.Phone'),
        ),
    ]
