# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacombine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='opt_in_source',
            field=models.CharField(choices=[('AO', 'Action by Owner'), ('AV', 'Action by Visitor')], max_length=2, null=True),
        ),
    ]
