# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacombine', '0003_auto_20170826_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='cc_id',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='constantcontactlist',
            name='cc_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cc_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='cc_id',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='cc_id',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
