# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacombine', '0004_auto_20170828_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='about',
        ),
        migrations.AddField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='datacombine.Contact'),
        ),
    ]
