# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 14:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacombine', '0006_Make_Contact_status_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiringRemediation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField()),
                ('contact_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacombine.Contact')),
            ],
        ),
    ]
