# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacombine', '0007_Added_a_class_for_remediations'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='source_details',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='cc_id',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
    ]
