# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacombine', '0008_Changes_made_to_create_new_contacts_to_push_to_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='cc_id',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='constantcontactlist',
            name='cc_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cc_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='cc_id',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
    ]
