# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacombine', '0010_Made_alterations_to_datetimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('BU', 'Business'), ('PE', 'Personal')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cc_modified_date',
            field=models.DateTimeField(auto_now_add=True, default='2017-09-16T23:20:33.648910+00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('UN', 'Unconfirmed'), ('AC', 'Active'), ('OP', 'Optout'), ('RE', 'Removed'), ('NO', 'Non Subscriber')], default='AO', max_length=2),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='confirm_status',
            field=models.CharField(choices=[('CO', 'Confirmed'), ('NC', 'No Confirmation Required')], default='CO', max_length=3),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='opt_in_date',
            field=models.DateTimeField(auto_now_add=True, default='2017-09-16T23:20:33.648910+00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='opt_in_source',
            field=models.CharField(choices=[('AO', 'Action by Owner'), ('AV', 'Action by Visitor')], default='AO', max_length=2),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='status',
            field=models.CharField(choices=[('UN', 'Unconfirmed'), ('AC', 'Active'), ('OP', 'Optout'), ('RE', 'Removed'), ('NO', 'Non Subscriber')], default='AC', max_length=2),
        ),
    ]
