# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacombine', '0011_Added_additional_constraints_for_pushing_new_contacts_to_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='confirmed',
            field=models.NullBooleanField(default=True),
        ),
    ]
